name: agility_redux
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  rxdart: ^0.24.1
  stack_trace: ^1.9.3
  logging: ^0.11.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
