name: agility_redux
description: Agility Redux is a modular, pluggable Redux state management library.
version: 0.0.4
homepage: https://github.com/songfei/agility_redux

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  meta: ^1.1.8
  rxdart: ^0.24.1
  stack_trace: ^1.9.3
  logging: ^0.11.4

dev_dependencies:
  test: ^1.15.3